#!/bin/bash

echo "🚀 Admin Management Migration Helper"
echo "===================================="
echo ""
echo "This migration adds the following to your Supabase database:"
echo "✅ 8 project status types (draft, template-internal, etc.)"
echo "✅ Deployment tracking fields for Netlify integration"
echo "✅ Enhanced account management (prospect/customer/inactive)"
echo "✅ Audit logging and version control tables"
echo "✅ Status transition tracking with validation"
echo "✅ Maintenance page support for paused projects"
echo ""
echo "To apply this migration, you have 3 options:"
echo ""
echo "Option 1: Supabase Dashboard (Recommended)"
echo "------------------------------------------"
echo "1. Go to: https://supabase.com/dashboard/project/bpdhbxvsguklkbusqtke/sql/new"
echo "2. Copy the contents of: supabase/migrations/20250117_admin_management_schema.sql"
echo "3. Paste into the SQL editor"
echo "4. Click 'Run'"
echo ""
echo "Option 2: Using Supabase CLI"
echo "----------------------------"
echo "If you have Supabase CLI installed:"
echo "$ supabase migration up"
echo ""
echo "Option 3: Direct PostgreSQL Connection"
echo "--------------------------------------"
echo "$ psql postgres://postgres.[project-ref]:[password]@aws-0-us-west-1.pooler.supabase.com:6543/postgres < supabase/migrations/20250117_admin_management_schema.sql"
echo ""
echo "After applying, verify the migration worked by checking:"
echo "- New columns in projects table (project_status, subdomain, etc.)"
echo "- New tables (project_versions, audit_logs, etc.)"
echo "- The project_management_view is created"