// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// This file is automatically generated by the Component Pipeline System
// Last updated: 2025-01-28

// Component registry types imported when needed

// Import all components currently in the system
import { Hero1, hero1Config } from '@/components/core/sections/hero1';
import { Hero2, hero2Config } from '@/components/core/sections/hero2';

/**
 * Auto-generated registry of all core components
 * Components are automatically registered here when created through the pipeline
 */
export const generatedComponents = {
  'hero1': {
    component: Hero1,
    config: hero1Config
  },
  'hero2': {
    component: Hero2,
    config: hero2Config
  }
};

// Export for runtime access
export default generatedComponents;