// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// This file is automatically generated by the Component Pipeline System
// Last updated: 2025-01-28

import { ComponentRegistry } from '@/lib/component-registry';

// Import the only component currently in the system
import { Hero1, hero1Config } from '@/components/core/sections/hero1';

/**
 * Auto-generated registry of all core components
 * Components are automatically registered here when created through the pipeline
 */
export const generatedComponents: ComponentRegistry = {
  'hero1': {
    component: Hero1,
    config: hero1Config
  }
};

// Export for runtime access
export default generatedComponents;